[package]
name = "jsonwrap"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
schemars.workspace = true
serde-reflection.workspace = true
serde_json.workspace = true
poem-openapi.workspace = true
