[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
foreign.workspace = true
jsonwrap.workspace = true

poem.workspace = true
poem-openapi.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
